### ISSUE TITLE
Using Your Plugin

### ISSUE THREAD

**Issue by raven2cz** [polywock/gptSearch#2]
I would like to use your plugin. The screenshots look good, and most importantly, it's a feature that I've been missing. However, you do not specify the license under which your plugin is published. Additionally, I can't even see the code on GitHub. How can I trust the plugin when I don't know what it does? So far, there are very few users, and moreover, Firefox writes: "This add-on is not actively monitored for security by Mozilla. Make sure you trust it before installing." So what's the status with the project?

**Comment by polywock** [comment]
Hello. Privacy is also a big concern for me so I understand your concerns. 

A little about me: I'm Polywock. I've been making extensions for years as a hobby. My most popular extension, Global Speed, has over 4M users across Edge, Chrome, and Firefox. None of my extensions have any telemetry, ads, or data collection. 


> However, you do not specify the license under which your plugin is published. Additionally, I can't even see the code on GitHub.

I haven't published the source code and I'm using Github purely for issue tracking. Maybe I will publish the source code once the user-base stabilizes. Usually I do publish source code for my extensions, but I have a nagging feeling the minute I do in this case, there will be five clones competing with me. 

> Firefox writes: "This add-on is not actively monitored for security by Mozilla. 

The Firefox add-on store gives that warning to nearly all extensions. The only way to remove that warning is if they choose you for their recommended program. My other extension,  [Global Speed](https://github.com/polywock/globalSpeed), with 65K users on the Firefox store also says the same thing.

> How can I trust the plugin when I don't know what it does? 

As for general security, the extension is screened by Google for the Chrome Web Store and Microsoft for the Edge Add-ons store (still in process of publishing). 

As for privacy, you can read the privacy policy [here](https://github.com/polywock/gptSearch/blob/main/PRIVACY_POLICY.md). 

To be clear, the extension only communicates with ChatGPT's API. Feel free to monitor network traffic. 

## Genuine privacy issue 

GPT Search caches chats locally to perform fast searches. If someone has access to your device, they might be able to read your cached chats. 

In the latest update, I've added an option called "Session-only caching" so the cached chats clear when you close Firefox.It will slow down searches, but if your device is shared, you might want to turn that on.

**Comment by polywock** [comment]
@raven2cz An update: the extension's source code is now available.
